### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by Jennie777555** [qiongwu86/URLLC-Awared-Resource-Allocation-for-Heterogeneous-Vehicular-Edge-Computing#8]
您好！请问代码是在哪个python版本下运行的呢？环境配置有什么要求呢？谢谢！

**Comment by wuhangwang** [comment]
> 您好！请问代码是在哪个python版本下运行的呢？环境配置有什么要求呢？谢谢！

您好 在python 3.7以上应该都能运行，环境配置也没有太多的要求，但需要torch，numpy等一些重要的库

**Comment by Jennie777555** [comment]
> > 您好！请问代码是在哪个python版本下运行的呢？环境配置有什么要求呢？谢谢！
> 
> 您好 在python 3.7以上应该都能运行，环境配置也没有太多的要求，但需要torch，numpy等一些重要的库

十分感谢您的分享！

**Comment by wkyd** [comment]
您好，请问我在运行时出现如下错误该如何解决，谢谢！：Traceback (most recent call last):
  File "F:\URLLC\URLLC\main_SAC.py", line 135, in <module>
    main()
  File "F:\URLLC\URLLC\main_SAC.py", line 67, in main
    state,r,utility_queue,utility,delay,action_comm,action= env.step(actor, memory,Model)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\URLLC\URLLC\Env_SAC.py", line 191, in step
    action,action_comm= actor.choose_action(state1,memory) # ndarray : [[a,b,c,d]] , [[a,b,c],[a,b,c],[a,b,c]]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\URLLC\URLLC\DRL_SAC.py", line 197, in choose_action
    action_comm = action_comm.data.numpy().flatten()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Process finished with exit code 1
